In [37]:
import pandas as pd

In [38]:
dataset=pd.read_csv('SensorFault_Detector.csv')

In [39]:
dataset

,Machine_ID,Machine_Type,Installation_Year,Operational_Hours,Temperature_C,Vibration_mms,Sound_dB,Oil_Level_pct,Coolant_Level_pct,Power_Consumption_kW,...,Failure_History_Count,AI_Supervision,Error_Codes_Last_30_Days,Remaining_Useful_Life_days,Failure_Within_7_Days,Laser_Intensity,Hydraulic_Pressure_bar,Coolant_Flow_L_min,Heat_Index,AI_Override_Events
0,MC_000000,Mixer,2027,81769,73.43,12.78,83.72,36.76,68.74,84.95,...,5,True,3,162.0,False,NaN,NaN,NaN,NaN,2
1,MC_000001,Industrial_Chiller,2032,74966,58.32,14.99,77.04,100.00,62.13,154.61,...,2,True,4,147.0,False,NaN,NaN,40.92,NaN,2
2,MC_000002,Pick_and_Place,2003,94006,49.63,23.78,69.08,42.96,35.96,51.90,...,1,True,6,0.0,True,NaN,NaN,NaN,NaN,2
3,MC_000003,Vision_System,2007,76637,63.73,12.38,85.58,94.90,48.94,75.61,...,1,False,4,161.0,False,NaN,NaN,NaN,NaN,0
4,MC_000004,Shuttle_System,2016,20870,42.77,4.42,96.72,47.56,53.78,224.93,...,2,False,1,765.0,False,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,MC_499995,Vacuum_Packer,2011,14425,65.42,16.50,81.95,59.21,73.67,255.87,...,3,False,0,820.0,False,NaN,NaN,NaN,NaN,0
499996,MC_499996,Conveyor_Belt,2003,75501,44.83,12.88,64.94,73.69,29.25,198.37,...,1,False,4,34.0,False,NaN,NaN,NaN,NaN,0
499997,MC_499997,CMM,2039,19855,37.26,11.46,70.70,70.70,49.04,156.59,...,2,False,4,815.0,False,NaN,NaN,NaN,NaN,0
499998,MC_499998,Dryer,2035,86823,67.72,16.76,77.45,97.00,15.40,132.33,...,2,True,0,99.0,False,NaN,NaN,NaN,NaN,2
499999,MC_499999,Industrial_Chiller,2021,52505,46.01,8.94,67.88,51.11,31.90,138.69,...,1,False,4,489.0,False,NaN,NaN,41.09,NaN,0

In [40]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 22 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Machine_ID                  500000 non-null  object
 1   Machine_Type                500000 non-null  object
 2   Installation_Year           500000 non-null  int64
 3   Operational_Hours           500000 non-null  int64
 4   Temperature_C               500000 non-null  float64
 5   Vibration_mms               500000 non-null  float64
 6   Sound_dB                    500000 non-null  float64
 7   Oil_Level_pct               500000 non-null  float64
 8   Coolant_Level_pct           500000 non-null  float64
 9   Power_Consumption_kW        500000 non-null  float64
 10  Last_Maintenance_Days_Ago   500000 non-null  int64
 11  Maintenance_History_Count   500000 non-null  int64
 12  Failure_History_Count       500000 non-null  int64
 13  AI_Supervision              500000 non-null  bool
 14  Error_Codes_Last_30_Days    500000 non-null  int64
 15  Remaining_Useful_Life_days  500000 non-null  float64
 16  Failure_Within_7_Days       500000 non-null  bool
 17  Laser_Intensity             15156 non-null   float64
 18  Hydraulic_Pressure_bar      30340 non-null   float64
 19  Coolant_Flow_L_min          45624 non-null   float64
 20  Heat_Index                  45214 non-null   float64
 21  AI_Override_Events          500000 non-null  int64
dtypes: bool(2), float64(11), int64(7), object(2)
memory usage: 77.2+ MB

In [41]:
dataset.columns

Index(['Machine_ID', 'Machine_Type', 'Installation_Year', 'Operational_Hours',
       'Temperature_C', 'Vibration_mms', 'Sound_dB', 'Oil_Level_pct',
       'Coolant_Level_pct', 'Power_Consumption_kW',
       'Last_Maintenance_Days_Ago', 'Maintenance_History_Count',
       'Failure_History_Count', 'AI_Supervision', 'Error_Codes_Last_30_Days',
       'Remaining_Useful_Life_days', 'Failure_Within_7_Days',
       'Laser_Intensity', 'Hydraulic_Pressure_bar', 'Coolant_Flow_L_min',
       'Heat_Index', 'AI_Override_Events'],
      dtype='object')

In [42]:
dataset.isnull().sum()

Machine_ID                         0
Machine_Type                       0
Installation_Year                  0
Operational_Hours                  0
Temperature_C                      0
Vibration_mms                      0
Sound_dB                           0
Oil_Level_pct                      0
Coolant_Level_pct                  0
Power_Consumption_kW               0
Last_Maintenance_Days_Ago          0
Maintenance_History_Count          0
Failure_History_Count              0
AI_Supervision                     0
Error_Codes_Last_30_Days           0
Remaining_Useful_Life_days         0
Failure_Within_7_Days              0
Laser_Intensity               484844
Hydraulic_Pressure_bar        469660
Coolant_Flow_L_min            454376
Heat_Index                    454786
AI_Override_Events                 0
dtype: int64

In [43]:
dataset['Laser_Intensity'].isnull().sum()

np.int64(484844)

In [44]:
dstaset=dataset.drop(['Machine_ID','Laser_Intensity','Hydraulic_Pressure_bar','Coolant_Flow_L_min','Heat_Index'],axis=1,inplace=True)

In [45]:
dataset

,Machine_Type,Installation_Year,Operational_Hours,Temperature_C,Vibration_mms,Sound_dB,Oil_Level_pct,Coolant_Level_pct,Power_Consumption_kW,Last_Maintenance_Days_Ago,Maintenance_History_Count,Failure_History_Count,AI_Supervision,Error_Codes_Last_30_Days,Remaining_Useful_Life_days,Failure_Within_7_Days,AI_Override_Events
0,Mixer,2027,81769,73.43,12.78,83.72,36.76,68.74,84.95,153,4,5,True,3,162.0,False,2
1,Industrial_Chiller,2032,74966,58.32,14.99,77.04,100.00,62.13,154.61,136,5,2,True,4,147.0,False,2
2,Pick_and_Place,2003,94006,49.63,23.78,69.08,42.96,35.96,51.90,258,1,1,True,6,0.0,True,2
3,Vision_System,2007,76637,63.73,12.38,85.58,94.90,48.94,75.61,43,4,1,False,4,161.0,False,0
4,Shuttle_System,2016,20870,42.77,4.42,96.72,47.56,53.78,224.93,346,4,2,False,1,765.0,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,Vacuum_Packer,2011,14425,65.42,16.50,81.95,59.21,73.67,255.87,282,4,3,False,0,820.0,False,0
499996,Conveyor_Belt,2003,75501,44.83,12.88,64.94,73.69,29.25,198.37,208,4,1,False,4,34.0,False,0
499997,CMM,2039,19855,37.26,11.46,70.70,70.70,49.04,156.59,185,7,2,False,4,815.0,False,0
499998,Dryer,2035,86823,67.72,16.76,77.45,97.00,15.40,132.33,274,3,2,True,0,99.0,False,2
499999,Industrial_Chiller,2021,52505,46.01,8.94,67.88,51.11,31.90,138.69,171,4,1,False,4,489.0,False,0

In [46]:
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)

In [47]:
dataset.isnull().sum()

Installation_Year                     0
Operational_Hours                     0
Temperature_C                         0
Vibration_mms                         0
Sound_dB                              0
Oil_Level_pct                         0
Coolant_Level_pct                     0
Power_Consumption_kW                  0
Last_Maintenance_Days_Ago             0
Maintenance_History_Count             0
Failure_History_Count                 0
AI_Supervision                        0
Error_Codes_Last_30_Days              0
Remaining_Useful_Life_days            0
Failure_Within_7_Days                 0
AI_Override_Events                    0
Machine_Type_AGV                      0
Machine_Type_Automated_Screwdriver    0
Machine_Type_Boiler                   0
Machine_Type_CMM                      0
Machine_Type_CNC_Lathe                0
Machine_Type_CNC_Mill                 0
Machine_Type_Carton_Former            0
Machine_Type_Compressor               0
Machine_Type_Conveyor_Belt            0
Machine_Type_Crane                    0
Machine_Type_Dryer                    0
Machine_Type_Forklift_Electric        0
Machine_Type_Furnace                  0
Machine_Type_Grinder                  0
Machine_Type_Heat_Exchanger           0
Machine_Type_Hydraulic_Press          0
Machine_Type_Industrial_Chiller       0
Machine_Type_Injection_Molder         0
Machine_Type_Labeler                  0
Machine_Type_Laser_Cutter             0
Machine_Type_Mixer                    0
Machine_Type_Palletizer               0
Machine_Type_Pick_and_Place           0
Machine_Type_Press_Brake              0
Machine_Type_Pump                     0
Machine_Type_Robot_Arm                0
Machine_Type_Shrink_Wrapper           0
Machine_Type_Shuttle_System           0
Machine_Type_Vacuum_Packer            0
Machine_Type_Valve_Controller         0
Machine_Type_Vision_System            0
Machine_Type_XRay_Inspector           0
dtype: int64

In [48]:
wrong_data = dataset['AI_Override_Events']=='AI_Override_Events'
dataset[wrong_data]

Empty DataFrame
Columns: [Installation_Year, Operational_Hours, Temperature_C, Vibration_mms, Sound_dB, Oil_Level_pct, Coolant_Level_pct, Power_Consumption_kW, Last_Maintenance_Days_Ago, Maintenance_History_Count, Failure_History_Count, AI_Supervision, Error_Codes_Last_30_Days, Remaining_Useful_Life_days, Failure_Within_7_Days, AI_Override_Events, Machine_Type_AGV, Machine_Type_Automated_Screwdriver, Machine_Type_Boiler, Machine_Type_CMM, Machine_Type_CNC_Lathe, Machine_Type_CNC_Mill, Machine_Type_Carton_Former, Machine_Type_Compressor, Machine_Type_Conveyor_Belt, Machine_Type_Crane, Machine_Type_Dryer, Machine_Type_Forklift_Electric, Machine_Type_Furnace, Machine_Type_Grinder, Machine_Type_Heat_Exchanger, Machine_Type_Hydraulic_Press, Machine_Type_Industrial_Chiller, Machine_Type_Injection_Molder, Machine_Type_Labeler, Machine_Type_Laser_Cutter, Machine_Type_Mixer, Machine_Type_Palletizer, Machine_Type_Pick_and_Place, Machine_Type_Press_Brake, Machine_Type_Pump, Machine_Type_Robot_Arm, Machine_Type_Shrink_Wrapper, Machine_Type_Shuttle_System, Machine_Type_Vacuum_Packer, Machine_Type_Valve_Controller, Machine_Type_Vision_System, Machine_Type_XRay_Inspector]
Index: []

[0 rows x 48 columns]

In [49]:
dataset

,Installation_Year,Operational_Hours,Temperature_C,Vibration_mms,Sound_dB,Oil_Level_pct,Coolant_Level_pct,Power_Consumption_kW,Last_Maintenance_Days_Ago,Maintenance_History_Count,...,Machine_Type_Pick_and_Place,Machine_Type_Press_Brake,Machine_Type_Pump,Machine_Type_Robot_Arm,Machine_Type_Shrink_Wrapper,Machine_Type_Shuttle_System,Machine_Type_Vacuum_Packer,Machine_Type_Valve_Controller,Machine_Type_Vision_System,Machine_Type_XRay_Inspector
0,2027,81769,73.43,12.78,83.72,36.76,68.74,84.95,153,4,...,0,0,0,0,0,0,0,0,0,0
1,2032,74966,58.32,14.99,77.04,100.00,62.13,154.61,136,5,...,0,0,0,0,0,0,0,0,0,0
2,2003,94006,49.63,23.78,69.08,42.96,35.96,51.90,258,1,...,1,0,0,0,0,0,0,0,0,0
3,2007,76637,63.73,12.38,85.58,94.90,48.94,75.61,43,4,...,0,0,0,0,0,0,0,0,1,0
4,2016,20870,42.77,4.42,96.72,47.56,53.78,224.93,346,4,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,2011,14425,65.42,16.50,81.95,59.21,73.67,255.87,282,4,...,0,0,0,0,0,0,1,0,0,0
499996,2003,75501,44.83,12.88,64.94,73.69,29.25,198.37,208,4,...,0,0,0,0,0,0,0,0,0,0
499997,2039,19855,37.26,11.46,70.70,70.70,49.04,156.59,185,7,...,0,0,0,0,0,0,0,0,0,0
499998,2035,86823,67.72,16.76,77.45,97.00,15.40,132.33,274,3,...,0,0,0,0,0,0,0,0,0,0
499999,2021,52505,46.01,8.94,67.88,51.11,31.90,138.69,171,4,...,0,0,0,0,0,0,0,0,0,0

In [50]:
dataset['AI_Override_Events'].value_counts()

AI_Override_Events
0     370058
1      40738
2      40465
3      27071
4      13632
5       5488
6       1844
7        533
8        142
9         23
10         4
11         2
Name: count, dtype: int64

In [51]:
dataset['AI_Supervision']=dataset['AI_Supervision'].astype('int64')
dataset['Failure_Within_7_Days']=dataset['Failure_Within_7_Days'].astype('int64')

In [52]:
dataset

,Installation_Year,Operational_Hours,Temperature_C,Vibration_mms,Sound_dB,Oil_Level_pct,Coolant_Level_pct,Power_Consumption_kW,Last_Maintenance_Days_Ago,Maintenance_History_Count,...,Machine_Type_Pick_and_Place,Machine_Type_Press_Brake,Machine_Type_Pump,Machine_Type_Robot_Arm,Machine_Type_Shrink_Wrapper,Machine_Type_Shuttle_System,Machine_Type_Vacuum_Packer,Machine_Type_Valve_Controller,Machine_Type_Vision_System,Machine_Type_XRay_Inspector
0,2027,81769,73.43,12.78,83.72,36.76,68.74,84.95,153,4,...,0,0,0,0,0,0,0,0,0,0
1,2032,74966,58.32,14.99,77.04,100.00,62.13,154.61,136,5,...,0,0,0,0,0,0,0,0,0,0
2,2003,94006,49.63,23.78,69.08,42.96,35.96,51.90,258,1,...,1,0,0,0,0,0,0,0,0,0
3,2007,76637,63.73,12.38,85.58,94.90,48.94,75.61,43,4,...,0,0,0,0,0,0,0,0,1,0
4,2016,20870,42.77,4.42,96.72,47.56,53.78,224.93,346,4,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,2011,14425,65.42,16.50,81.95,59.21,73.67,255.87,282,4,...,0,0,0,0,0,0,1,0,0,0
499996,2003,75501,44.83,12.88,64.94,73.69,29.25,198.37,208,4,...,0,0,0,0,0,0,0,0,0,0
499997,2039,19855,37.26,11.46,70.70,70.70,49.04,156.59,185,7,...,0,0,0,0,0,0,0,0,0,0
499998,2035,86823,67.72,16.76,77.45,97.00,15.40,132.33,274,3,...,0,0,0,0,0,0,0,0,0,0
499999,2021,52505,46.01,8.94,67.88,51.11,31.90,138.69,171,4,...,0,0,0,0,0,0,0,0,0,0

In [53]:
# Save your dataframe directly to a local CSV file
prep=dataset.to_csv('sensor_failure_analysis.csv', index=False)

In [55]:
prep=pd.read_csv('sensor_failure_analysis.csv')

In [56]:
prep

,Installation_Year,Operational_Hours,Temperature_C,Vibration_mms,Sound_dB,Oil_Level_pct,Coolant_Level_pct,Power_Consumption_kW,Last_Maintenance_Days_Ago,Maintenance_History_Count,...,Machine_Type_Pick_and_Place,Machine_Type_Press_Brake,Machine_Type_Pump,Machine_Type_Robot_Arm,Machine_Type_Shrink_Wrapper,Machine_Type_Shuttle_System,Machine_Type_Vacuum_Packer,Machine_Type_Valve_Controller,Machine_Type_Vision_System,Machine_Type_XRay_Inspector
0,2027,81769,73.43,12.78,83.72,36.76,68.74,84.95,153,4,...,0,0,0,0,0,0,0,0,0,0
1,2032,74966,58.32,14.99,77.04,100.00,62.13,154.61,136,5,...,0,0,0,0,0,0,0,0,0,0
2,2003,94006,49.63,23.78,69.08,42.96,35.96,51.90,258,1,...,1,0,0,0,0,0,0,0,0,0
3,2007,76637,63.73,12.38,85.58,94.90,48.94,75.61,43,4,...,0,0,0,0,0,0,0,0,1,0
4,2016,20870,42.77,4.42,96.72,47.56,53.78,224.93,346,4,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,2011,14425,65.42,16.50,81.95,59.21,73.67,255.87,282,4,...,0,0,0,0,0,0,1,0,0,0
499996,2003,75501,44.83,12.88,64.94,73.69,29.25,198.37,208,4,...,0,0,0,0,0,0,0,0,0,0
499997,2039,19855,37.26,11.46,70.70,70.70,49.04,156.59,185,7,...,0,0,0,0,0,0,0,0,0,0
499998,2035,86823,67.72,16.76,77.45,97.00,15.40,132.33,274,3,...,0,0,0,0,0,0,0,0,0,0
499999,2021,52505,46.01,8.94,67.88,51.11,31.90,138.69,171,4,...,0,0,0,0,0,0,0,0,0,0