# Import Libraries:

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

/home/kethziyal19/.local/lib/python3.11/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

# Load the Dataset :

In [2]:
dataset=pd.read_csv("sensor_failure_analysis.csv")

In [3]:
#print(np.__version__)

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 48 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Installation_Year                   500000 non-null  int64
 1   Operational_Hours                   500000 non-null  int64
 2   Temperature_C                       500000 non-null  float64
 3   Vibration_mms                       500000 non-null  float64
 4   Sound_dB                            500000 non-null  float64
 5   Oil_Level_pct                       500000 non-null  float64
 6   Coolant_Level_pct                   500000 non-null  float64
 7   Power_Consumption_kW                500000 non-null  float64
 8   Last_Maintenance_Days_Ago           500000 non-null  int64
 9   Maintenance_History_Count           500000 non-null  int64
 10  Failure_History_Count               500000 non-null  int64
 11  AI_Supervision                      500000 non-null  int64
 12  Error_Codes_Last_30_Days            500000 non-null  int64
 13  Remaining_Useful_Life_days          500000 non-null  float64
 14  Failure_Within_7_Days               500000 non-null  int64
 15  AI_Override_Events                  500000 non-null  int64
 16  Machine_Type_AGV                    500000 non-null  int64
 17  Machine_Type_Automated_Screwdriver  500000 non-null  int64
 18  Machine_Type_Boiler                 500000 non-null  int64
 19  Machine_Type_CMM                    500000 non-null  int64
 20  Machine_Type_CNC_Lathe              500000 non-null  int64
 21  Machine_Type_CNC_Mill               500000 non-null  int64
 22  Machine_Type_Carton_Former          500000 non-null  int64
 23  Machine_Type_Compressor             500000 non-null  int64
 24  Machine_Type_Conveyor_Belt          500000 non-null  int64
 25  Machine_Type_Crane                  500000 non-null  int64
 26  Machine_Type_Dryer                  500000 non-null  int64
 27  Machine_Type_Forklift_Electric      500000 non-null  int64
 28  Machine_Type_Furnace                500000 non-null  int64
 29  Machine_Type_Grinder                500000 non-null  int64
 30  Machine_Type_Heat_Exchanger         500000 non-null  int64
 31  Machine_Type_Hydraulic_Press        500000 non-null  int64
 32  Machine_Type_Industrial_Chiller     500000 non-null  int64
 33  Machine_Type_Injection_Molder       500000 non-null  int64
 34  Machine_Type_Labeler                500000 non-null  int64
 35  Machine_Type_Laser_Cutter           500000 non-null  int64
 36  Machine_Type_Mixer                  500000 non-null  int64
 37  Machine_Type_Palletizer             500000 non-null  int64
 38  Machine_Type_Pick_and_Place         500000 non-null  int64
 39  Machine_Type_Press_Brake            500000 non-null  int64
 40  Machine_Type_Pump                   500000 non-null  int64
 41  Machine_Type_Robot_Arm              500000 non-null  int64
 42  Machine_Type_Shrink_Wrapper         500000 non-null  int64
 43  Machine_Type_Shuttle_System         500000 non-null  int64
 44  Machine_Type_Vacuum_Packer          500000 non-null  int64
 45  Machine_Type_Valve_Controller       500000 non-null  int64
 46  Machine_Type_Vision_System          500000 non-null  int64
 47  Machine_Type_XRay_Inspector         500000 non-null  int64
dtypes: float64(7), int64(41)
memory usage: 183.1 MB

In [5]:
dataset

,Installation_Year,Operational_Hours,Temperature_C,Vibration_mms,Sound_dB,Oil_Level_pct,Coolant_Level_pct,Power_Consumption_kW,Last_Maintenance_Days_Ago,Maintenance_History_Count,...,Machine_Type_Pick_and_Place,Machine_Type_Press_Brake,Machine_Type_Pump,Machine_Type_Robot_Arm,Machine_Type_Shrink_Wrapper,Machine_Type_Shuttle_System,Machine_Type_Vacuum_Packer,Machine_Type_Valve_Controller,Machine_Type_Vision_System,Machine_Type_XRay_Inspector
0,2027,81769,73.43,12.78,83.72,36.76,68.74,84.95,153,4,...,0,0,0,0,0,0,0,0,0,0
1,2032,74966,58.32,14.99,77.04,100.00,62.13,154.61,136,5,...,0,0,0,0,0,0,0,0,0,0
2,2003,94006,49.63,23.78,69.08,42.96,35.96,51.90,258,1,...,1,0,0,0,0,0,0,0,0,0
3,2007,76637,63.73,12.38,85.58,94.90,48.94,75.61,43,4,...,0,0,0,0,0,0,0,0,1,0
4,2016,20870,42.77,4.42,96.72,47.56,53.78,224.93,346,4,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,2011,14425,65.42,16.50,81.95,59.21,73.67,255.87,282,4,...,0,0,0,0,0,0,1,0,0,0
499996,2003,75501,44.83,12.88,64.94,73.69,29.25,198.37,208,4,...,0,0,0,0,0,0,0,0,0,0
499997,2039,19855,37.26,11.46,70.70,70.70,49.04,156.59,185,7,...,0,0,0,0,0,0,0,0,0,0
499998,2035,86823,67.72,16.76,77.45,97.00,15.40,132.33,274,3,...,0,0,0,0,0,0,0,0,0,0
499999,2021,52505,46.01,8.94,67.88,51.11,31.90,138.69,171,4,...,0,0,0,0,0,0,0,0,0,0

# Load the Preprocessed Dataset

In [6]:
dataset=pd.read_csv("sensor_failure_analysis.csv",nrows=20000)

In [7]:
dataset.columns

Index(['Installation_Year', 'Operational_Hours', 'Temperature_C',
       'Vibration_mms', 'Sound_dB', 'Oil_Level_pct', 'Coolant_Level_pct',
       'Power_Consumption_kW', 'Last_Maintenance_Days_Ago',
       'Maintenance_History_Count', 'Failure_History_Count', 'AI_Supervision',
       'Error_Codes_Last_30_Days', 'Remaining_Useful_Life_days',
       'Failure_Within_7_Days', 'AI_Override_Events', 'Machine_Type_AGV',
       'Machine_Type_Automated_Screwdriver', 'Machine_Type_Boiler',
       'Machine_Type_CMM', 'Machine_Type_CNC_Lathe', 'Machine_Type_CNC_Mill',
       'Machine_Type_Carton_Former', 'Machine_Type_Compressor',
       'Machine_Type_Conveyor_Belt', 'Machine_Type_Crane',
       'Machine_Type_Dryer', 'Machine_Type_Forklift_Electric',
       'Machine_Type_Furnace', 'Machine_Type_Grinder',
       'Machine_Type_Heat_Exchanger', 'Machine_Type_Hydraulic_Press',
       'Machine_Type_Industrial_Chiller', 'Machine_Type_Injection_Molder',
       'Machine_Type_Labeler', 'Machine_Type_Laser_Cutter',
       'Machine_Type_Mixer', 'Machine_Type_Palletizer',
       'Machine_Type_Pick_and_Place', 'Machine_Type_Press_Brake',
       'Machine_Type_Pump', 'Machine_Type_Robot_Arm',
       'Machine_Type_Shrink_Wrapper', 'Machine_Type_Shuttle_System',
       'Machine_Type_Vacuum_Packer', 'Machine_Type_Valve_Controller',
       'Machine_Type_Vision_System', 'Machine_Type_XRay_Inspector'],
      dtype='object')

In [8]:
#dataset=dataset.drop(['Machine_ID','Laser_Intensity','Hydraulic_Pressure_bar','Coolant_Flow_L_min','Heat_Index'],axis=1,inplace=True)

In [9]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [10]:
dataset

,Installation_Year,Operational_Hours,Temperature_C,Vibration_mms,Sound_dB,Oil_Level_pct,Coolant_Level_pct,Power_Consumption_kW,Last_Maintenance_Days_Ago,Maintenance_History_Count,...,Machine_Type_Pick_and_Place,Machine_Type_Press_Brake,Machine_Type_Pump,Machine_Type_Robot_Arm,Machine_Type_Shrink_Wrapper,Machine_Type_Shuttle_System,Machine_Type_Vacuum_Packer,Machine_Type_Valve_Controller,Machine_Type_Vision_System,Machine_Type_XRay_Inspector
0,2027,81769,73.43,12.78,83.72,36.76,68.74,84.95,153,4,...,0,0,0,0,0,0,0,0,0,0
1,2032,74966,58.32,14.99,77.04,100.00,62.13,154.61,136,5,...,0,0,0,0,0,0,0,0,0,0
2,2003,94006,49.63,23.78,69.08,42.96,35.96,51.90,258,1,...,1,0,0,0,0,0,0,0,0,0
3,2007,76637,63.73,12.38,85.58,94.90,48.94,75.61,43,4,...,0,0,0,0,0,0,0,0,1,0
4,2016,20870,42.77,4.42,96.72,47.56,53.78,224.93,346,4,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2018,60753,59.40,11.30,63.91,58.05,81.60,175.70,297,4,...,0,0,0,0,0,0,0,0,0,0
19996,2010,94496,64.36,13.78,70.78,69.15,63.72,118.38,269,4,...,0,0,0,0,0,0,0,0,0,0
19997,2039,73382,67.53,11.12,87.99,87.66,55.77,177.88,4,5,...,0,0,0,0,0,0,0,0,0,0
19998,2039,86027,60.28,8.23,58.63,99.33,97.17,210.49,356,5,...,0,0,0,0,0,0,0,0,0,0
19999,2028,94847,57.05,10.61,67.69,22.27,49.16,150.47,47,7,...,0,0,0,0,0,0,0,0,0,0

# Input and Output Columns Separation:

In [11]:
indep=dataset[[ 'Operational_Hours', 'Temperature_C', 'Vibration_mms', 'Oil_Level_pct', 'Remaining_Useful_Life_days']]
indep

,Operational_Hours,Temperature_C,Vibration_mms,Oil_Level_pct,Remaining_Useful_Life_days
0,81769,73.43,12.78,36.76,162.0
1,74966,58.32,14.99,100.00,147.0
2,94006,49.63,23.78,42.96,0.0
3,76637,63.73,12.38,94.90,161.0
4,20870,42.77,4.42,47.56,765.0
...,...,...,...,...,...
19995,60753,59.40,11.30,58.05,299.0
19996,94496,64.36,13.78,69.15,0.0
19997,73382,67.53,11.12,87.66,296.0
19998,86027,60.28,8.23,99.33,160.0
19999,94847,57.05,10.61,22.27,49.0

In [12]:
dep=dataset[['Failure_Within_7_Days']]
dep

       Failure_Within_7_Days
0                          0
1                          0
2                          1
3                          0
4                          0
...                      ...
19995                      0
19996                      1
19997                      0
19998                      0
19999                      0

[20000 rows x 1 columns]

In [13]:
dataset["Failure_Within_7_Days"].value_counts()

Failure_Within_7_Days
0    18804
1     1196
Name: count, dtype: int64

# Train and Test dataset Split:

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [16]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid={'n_estimators':[10,50,100], 'criterion':['entropy','log_loss','gini'],
            'random_state':[0],'max_features':['sqrt','log2',None]}
grid=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['entropy', 'log_loss', 'gini'],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [10, 50, 100], 'random_state': [0]},
             verbose=3)

In [17]:
re=grid.cv_results_

grid_predictions=grid.predict(X_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)


from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 10, 'random_state': 0}: 1.0

In [18]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 10, 'random_state': 0}

In [19]:
print("The Confusion matrix:\n",cm)

The Confusion matrix:
 [[6275    0]
 [   0  392]]

In [20]:
print("The Classification Report matrix:\n",clf_report)

The Classification Report matrix:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      6275
           1       1.00      1.00      1.00       392

    accuracy                           1.00      6667
   macro avg       1.00      1.00      1.00      6667
weighted avg       1.00      1.00      1.00      6667

In [21]:
print("The f1_score:\n",f1_macro)

The f1_score:
 1.0

In [22]:
table=pd.DataFrame.from_dict(re)

In [23]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,param_random_state,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.597836,0.136370,0.074991,0.030539,entropy,sqrt,10,0,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
1,1.684274,0.323547,0.076815,0.013777,entropy,sqrt,50,0,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
2,3.301044,0.920021,0.119734,0.034374,entropy,sqrt,100,0,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
3,0.417260,0.115729,0.042212,0.006048,entropy,log2,10,0,"{'criterion': 'entropy', 'max_features': 'log2...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
4,1.682925,0.391392,0.085168,0.016905,entropy,log2,50,0,"{'criterion': 'entropy', 'max_features': 'log2...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
5,3.581501,0.727583,0.158166,0.052008,entropy,log2,100,0,"{'criterion': 'entropy', 'max_features': 'log2...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
6,0.399908,0.090932,0.046441,0.015359,entropy,None,10,0,"{'criterion': 'entropy', 'max_features': None,...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
7,1.793003,0.417387,0.052897,0.006681,entropy,None,50,0,"{'criterion': 'entropy', 'max_features': None,...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
8,3.140201,0.719554,0.091000,0.015336,entropy,None,100,0,"{'criterion': 'entropy', 'max_features': None,...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
9,0.588305,0.170124,0.038865,0.001988,log_loss,sqrt,10,0,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
10,1.692702,0.373036,0.080235,0.018938,log_loss,sqrt,50,0,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
11,2.980865,0.686540,0.120777,0.036595,log_loss,sqrt,100,0,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
12,0.542901,0.043876,0.042713,0.007425,log_loss,log2,10,0,"{'criterion': 'log_loss', 'max_features': 'log...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
13,1.746937,0.403350,0.098154,0.044562,log_loss,log2,50,0,"{'criterion': 'log_loss', 'max_features': 'log...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
14,3.342718,0.632544,0.127963,0.026125,log_loss,log2,100,0,"{'criterion': 'log_loss', 'max_features': 'log...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
15,0.647590,0.053625,0.071872,0.029912,log_loss,None,10,0,"{'criterion': 'log_loss', 'max_features': None...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
16,1.783740,0.403769,0.059974,0.005582,log_loss,None,50,0,"{'criterion': 'log_loss', 'max_features': None...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
17,3.587751,0.759390,0.093864,0.012528,log_loss,None,100,0,"{'criterion': 'log_loss', 'max_features': None...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
18,0.299373,0.056807,0.033030,0.002647,gini,sqrt,10,0,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
19,1.388399,0.190808,0.078771,0.026338,gini,sqrt,50,0,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
20,2.793872,0.650730,0.096596,0.010946,gini,sqrt,100,0,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
21,0.462972,0.030779,0.043590,0.002457,gini,log2,10,0,"{'criterion': 'gini', 'max_features': 'log2', ...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
22,1.701440,0.332931,0.072530,0.014613,gini,log2,50,0,"{'criterion': 'gini', 'max_features': 'log2', ...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
23,2.797842,0.597404,0.086585,0.008439,gini,log2,100,0,"{'criterion': 'gini', 'max_features': 'log2', ...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
24,0.380993,0.009343,0.038498,0.002323,gini,None,10,0,"{'criterion': 'gini', 'max_features': None, 'n...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
25,1.639150,0.351726,0.063276,0.008239,gini,None,50,0,"{'criterion': 'gini', 'max_features': None, 'n...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1
26,2.313437,0.208550,0.060406,0.019397,gini,None,100,0,"{'criterion': 'gini', 'max_features': None, 'n...",1.0,1.0,1.0,1.0,1.0,1.0,0.0,1

In [24]:
table_pr=pd.DataFrame()

In [25]:
print(type(table_pr))

<class 'pandas.core.frame.DataFrame'>

In [26]:
print(X_test)

       Operational_Hours  Temperature_C  Vibration_mms  Oil_Level_pct  \
19134              98511          58.09           7.07          78.86
4981               89398          70.33          10.66          87.03
16643               6845          62.49           5.33          81.30
19117              89640          53.91           3.64          95.46
5306               64041          69.03          12.86          81.88
...                  ...            ...            ...            ...
16742              80523          40.48           9.96          76.91
7332                6313          14.10          10.66          35.27
15345              81646          28.51           3.89          74.80
5337               69188          41.73          12.32          73.31
13597              47224          37.50           7.46          44.43

       Remaining_Useful_Life_days
19134                        25.0
4981                          0.0
16643                       871.0
19117                        83.0
5306                        298.0
...                           ...
16742                       183.0
7332                        871.0
15345                       223.0
5337                        320.0
13597                       519.0

[6667 rows x 5 columns]

In [27]:
table_pr['Operational_Hours']=X_test["Operational_Hours"]
table_pr['Temperature_C']=X_test["Temperature_C"]
table_pr['Vibration_mms']=X_test["Vibration_mms"]
table_pr['Oil_Level_pct']=X_test["Oil_Level_pct"]
table_pr['Remaining_Useful_Life_days']=X_test["Remaining_Useful_Life_days"]

In [28]:
table_pr = X_test.copy()

table_pr.to_csv("cm.csv", index=False)

In [29]:
table_pr['Actual'] = y_test
table_pr['Predicted'] = grid_predictions

In [30]:
dataset

,Installation_Year,Operational_Hours,Temperature_C,Vibration_mms,Sound_dB,Oil_Level_pct,Coolant_Level_pct,Power_Consumption_kW,Last_Maintenance_Days_Ago,Maintenance_History_Count,...,Machine_Type_Pick_and_Place,Machine_Type_Press_Brake,Machine_Type_Pump,Machine_Type_Robot_Arm,Machine_Type_Shrink_Wrapper,Machine_Type_Shuttle_System,Machine_Type_Vacuum_Packer,Machine_Type_Valve_Controller,Machine_Type_Vision_System,Machine_Type_XRay_Inspector
0,2027,81769,73.43,12.78,83.72,36.76,68.74,84.95,153,4,...,0,0,0,0,0,0,0,0,0,0
1,2032,74966,58.32,14.99,77.04,100.00,62.13,154.61,136,5,...,0,0,0,0,0,0,0,0,0,0
2,2003,94006,49.63,23.78,69.08,42.96,35.96,51.90,258,1,...,1,0,0,0,0,0,0,0,0,0
3,2007,76637,63.73,12.38,85.58,94.90,48.94,75.61,43,4,...,0,0,0,0,0,0,0,0,1,0
4,2016,20870,42.77,4.42,96.72,47.56,53.78,224.93,346,4,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,2018,60753,59.40,11.30,63.91,58.05,81.60,175.70,297,4,...,0,0,0,0,0,0,0,0,0,0
19996,2010,94496,64.36,13.78,70.78,69.15,63.72,118.38,269,4,...,0,0,0,0,0,0,0,0,0,0
19997,2039,73382,67.53,11.12,87.99,87.66,55.77,177.88,4,5,...,0,0,0,0,0,0,0,0,0,0
19998,2039,86027,60.28,8.23,58.63,99.33,97.17,210.49,356,5,...,0,0,0,0,0,0,0,0,0,0
19999,2028,94847,57.05,10.61,67.69,22.27,49.16,150.47,47,7,...,0,0,0,0,0,0,0,0,0,0

In [31]:
Operational_Hours_input=int(input("Operational_Hours:"))
Temperature_C_input=float(input("Temperature_C:"))
Vibration_mms_input=float(input("Vibration_mms:"))
Oil_Level_pct_input=float(input("Oil_Level_pct:"))
Remaining_Useful_Life_days_input=int(input("Remaining_Useful_Life_days:"))

Operational_Hours:94006
Temperature_C:49.63
Vibration_mms:23.78
Oil_Level_pct:42.96
Remaining_Useful_Life_days:0

In [32]:
print(X_train.columns)

Index(['Operational_Hours', 'Temperature_C', 'Vibration_mms', 'Oil_Level_pct',
       'Remaining_Useful_Life_days'],
      dtype='object')

In [33]:
Future_Prediction=grid.predict([[Operational_Hours_input,Temperature_C_input,Vibration_mms_input,
                                 Oil_Level_pct_input,Remaining_Useful_Life_days_input]])
print("Future Prediction={}".format(Future_Prediction))

Future Prediction=[1]

/home/kethziyal19/.local/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [34]:
if Future_Prediction == 0:
    print("Embedded Machine operates with Sensor Healthy: {}".format(Future_Prediction))
else:
    print("Embedded Machine operates with Sensor Faulty: {}".format(Future_Prediction))

Embedded Machine operates with Sensor Faulty: [1]